/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.cUsuario;
import Modulos.mPersona;
import Modulos.mUsuario;
import java.awt.event.ActionEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import jdk.nashorn.internal.runtime.JSType;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseListener;
import java.sql.SQLException;

/**
 *
 * @author Colo-PC
 */
public final class vGestion_Usuarios extends javax.swing.JFrame {

    /**
     * Creates new form vGestion_Usuarios
     */
    public vGestion_Usuarios() {
        initComponents();
        Mostrar();
        ocultar_columnas();
        jTextNombre_Usuario.requestFocus();
        this.jBotonSalir2_Usuario.setVisible(false);
        this.jEtiqID_Usuario.setVisible(false);
        this.jTextID_Usuario.setVisible(false);
        this.jBotonModif_Usuario.setEnabled(false);
        this.jBotonElim_Usuario.setEnabled(false);
        this.jBotonCancel_Usuario.setVisible(false);

        jTextID_Usuario.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if (!(Character.isDigit(c)) || (c == KeyEvent.VK_BACK_SPACE)) {
                    getToolkit().beep();
                    e.consume();
                }
            }
        });

        jTextNombre_Usuario.addKeyListener(new KeyAdapter() {

            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();

                if ((Character.isDigit(c))) {
                    getToolkit().beep();
                    e.consume();
                }
            }

        });

        jTabla_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {

                    int i = JOptionPane.showConfirmDialog(null, "Esta seguro que desea Modificar?", "Confirmar", JOptionPane.YES_NO_OPTION);
                    if (i == 0) {
                        jEtiqID_Usuario.setVisible(true);
                        jTextID_Usuario.setVisible(true);
                        jBotonModif_Usuario.setEnabled(true);
                        jBotonElim_Usuario.setEnabled(true);
                        jBotonAcep_Usuario.setEnabled(false);
                        jBotonCancel_Usuario.setVisible(true);

                        int fila = jTabla_Usuario.rowAtPoint(e.getPoint());
                        jTextID_Usuario.setText(jTabla_Usuario.getValueAt(fila, 0).toString());
                        jTextNombre_Usuario.setText(jTabla_Usuario.getValueAt(fila, 1).toString());
                        jTextApellido_Usuario.setText(jTabla_Usuario.getValueAt(fila, 2).toString());
                        jTextDomicilio_Usuario.setText(jTabla_Usuario.getValueAt(fila, 3).toString());
                        jTextTelefono_Usuario.setText(jTabla_Usuario.getValueAt(fila, 4).toString());
                        jTextCorreo_Usuario.setText(jTabla_Usuario.getValueAt(fila, 5).toString());
                        jTextNomUser_Usuario.setText(jTabla_Usuario.getValueAt(fila, 6).toString());
                        jTextPass_Usuario.setText(jTabla_Usuario.getValueAt(fila, 7).toString());
                        jComboAcceso_Usuario.setSelectedItem(jTabla_Usuario.getValueAt(fila, 8).toString());
                        jComboEstado_Usuario.setSelectedItem(jTabla_Usuario.getValueAt(fila, 9).toString());
                    } else {
                        jBotonAcep_Usuario.setEnabled(true);
                        jEtiqID_Usuario.setVisible(false);
                        jTextID_Usuario.setVisible(false);
                        jBotonModif_Usuario.setEnabled(false);
                        jBotonElim_Usuario.setEnabled(false);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void ocultar_columnas() {
        jTabla_Usuario.getColumnModel().getColumn(5).setMaxWidth(0);
        jTabla_Usuario.getColumnModel().getColumn(5).setMinWidth(0);
        jTabla_Usuario.getColumnModel().getColumn(5).setPreferredWidth(0);
        jTabla_Usuario.getColumnModel().getColumn(7).setMaxWidth(0);
        jTabla_Usuario.getColumnModel().getColumn(7).setMinWidth(0);
        jTabla_Usuario.getColumnModel().getColumn(7).setPreferredWidth(0);
    }

    public void Mostrar() {
        try {
            DefaultTableModel model;
            cUsuario obtdatos = new cUsuario();
            model = obtdatos.MostrarDatos();

            jTabla_Usuario.setModel(model);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    public void Limpiar() {
        jTextNombre_Usuario.setText("");
        jTextApellido_Usuario.setText("");
        jTextDomicilio_Usuario.setText("");
        jTextTelefono_Usuario.setText("");
        jTextCorreo_Usuario.setText("");
        jTextNomUser_Usuario.setText("");
        jTextPass_Usuario.setText("");
        jTextID_Usuario.setText("");
    }

    /* public void verificar(){
        try{
          cUsuario obtdatos = new cUsuario();
          int dato = obtdatos.VerificarLogin();
          if(dato > 0){
              JOptionPane.showMessageDialog(null, "Hay usuarios con los mismos nombres");
          }else{
              JOptionPane.showMessageDialog(null, "Usuario unico");
          }
        }catch (Exception e){
            
        }
    }*/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LTit_Usuario = new javax.swing.JLabel();
        jTextNombre_Usuario = new javax.swing.JTextField();
        jTextApellido_Usuario = new javax.swing.JTextField();
        jTextDomicilio_Usuario = new javax.swing.JTextField();
        jTextTelefono_Usuario = new javax.swing.JTextField();
        jTextCorreo_Usuario = new javax.swing.JTextField();
        jTextNomUser_Usuario = new javax.swing.JTextField();
        jEtiqNombre_Usuario = new javax.swing.JLabel();
        jEtiqApellido_Usuario = new javax.swing.JLabel();
        jEtiqDomicilio_Usuario = new javax.swing.JLabel();
        jEtiqTelefono_Usuario = new javax.swing.JLabel();
        jEtiqCorreo_Usuario = new javax.swing.JLabel();
        jEtiqNomUser_Usuario = new javax.swing.JLabel();
        jEtiqPass_Usuario = new javax.swing.JLabel();
        jBotonAcep_Usuario = new javax.swing.JButton();
        jBotonSalir_Usuario = new javax.swing.JButton();
        jComboAcceso_Usuario = new javax.swing.JComboBox<>();
        jEtiqAcceso_Usuario = new javax.swing.JLabel();
        jEtiqEstado_Usuario = new javax.swing.JLabel();
        jComboEstado_Usuario = new javax.swing.JComboBox<>();
        jBotonModif_Usuario = new javax.swing.JButton();
        jTextPass_Usuario = new javax.swing.JTextField();
        jTextID_Usuario = new javax.swing.JTextField();
        jEtiqID_Usuario = new javax.swing.JLabel();
        jBotonElim_Usuario = new javax.swing.JButton();
        jBotonCancel_Usuario = new javax.swing.JButton();
        jBotonSalir2_Usuario = new javax.swing.JButton();
        JSP1_Usuario = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabla_Usuario = jTabla_Usuario = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false; //Disallow the editing of any cell
            }
        };

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrar Usuarios");
        setName("Frame_Usuario"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LTit_Usuario.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        LTit_Usuario.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LTit_Usuario.setText("Gestion de Usuarios");
        LTit_Usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(LTit_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 180, 30));

        jTextNombre_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNombre_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextNombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 110, -1));

        jTextApellido_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextApellido_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextApellido_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 110, -1));

        jTextDomicilio_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextDomicilio_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextDomicilio_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 290, -1));

        jTextTelefono_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextTelefono_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextTelefono_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 220, -1));

        jTextCorreo_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextCorreo_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextCorreo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 270, -1));

        jTextNomUser_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextNomUser_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextNomUser_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 140, -1));

        jEtiqNombre_Usuario.setText("Nombre");
        getContentPane().add(jEtiqNombre_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, 20));

        jEtiqApellido_Usuario.setText("Apellido");
        getContentPane().add(jEtiqApellido_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, 20));

        jEtiqDomicilio_Usuario.setText("Domicilio");
        getContentPane().add(jEtiqDomicilio_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 20));

        jEtiqTelefono_Usuario.setText("Telefono - Contacto");
        getContentPane().add(jEtiqTelefono_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 140, 20));

        jEtiqCorreo_Usuario.setText("Correo Electronico - Contacto");
        getContentPane().add(jEtiqCorreo_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 170, 20));

        jEtiqNomUser_Usuario.setText("Usuario");
        getContentPane().add(jEtiqNomUser_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, 20));

        jEtiqPass_Usuario.setText("Contraseña");
        getContentPane().add(jEtiqPass_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, 20));

        jBotonAcep_Usuario.setText("Aceptar");
        jBotonAcep_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAcep_UsuarioActionPerformed(evt);
            }
        });
        jBotonAcep_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBotonAcep_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jBotonAcep_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 80, 30));

        jBotonSalir_Usuario.setText("Salir");
        jBotonSalir_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSalir_UsuarioActionPerformed(evt);
            }
        });
        jBotonSalir_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBotonSalir_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jBotonSalir_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 80, 30));

        jComboAcceso_Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Usuario Común" }));
        jComboAcceso_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboAcceso_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jComboAcceso_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 120, 20));

        jEtiqAcceso_Usuario.setText("Acceso");
        getContentPane().add(jEtiqAcceso_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 70, 20));

        jEtiqEstado_Usuario.setText("Estado");
        getContentPane().add(jEtiqEstado_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 50, 20));

        jComboEstado_Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
        getContentPane().add(jComboEstado_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 120, -1));

        jBotonModif_Usuario.setText("Editar");
        jBotonModif_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonModif_UsuarioActionPerformed(evt);
            }
        });
        jBotonModif_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBotonModif_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jBotonModif_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, -1, 30));

        jTextPass_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextPass_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextPass_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 270, -1));
        getContentPane().add(jTextID_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 30, 20));

        jEtiqID_Usuario.setText("Seleccione N°");
        getContentPane().add(jEtiqID_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, -1, 20));

        jBotonElim_Usuario.setText("Eliminar");
        jBotonElim_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonElim_UsuarioActionPerformed(evt);
            }
        });
        jBotonElim_Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBotonElim_UsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jBotonElim_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, 30));

        jBotonCancel_Usuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jBotonCancel_Usuario.setText("Cancelar");
        jBotonCancel_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonCancel_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jBotonCancel_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 80, 30));

        jBotonSalir2_Usuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        jBotonSalir2_Usuario.setText("Salir");
        jBotonSalir2_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSalir2_UsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jBotonSalir2_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(1205, 435, 70, 30));

        JSP1_Usuario.setFocusable(false);

        jTabla_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabla_Usuario);

        JSP1_Usuario.setViewportView(jScrollPane1);

        getContentPane().add(JSP1_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 690, 350));

        setSize(new java.awt.Dimension(1297, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jBotonAcep_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAcep_UsuarioActionPerformed

        cUsuario funcion = new cUsuario();
        mUsuario datos = new mUsuario();

        if (jTextNombre_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Nombre");
            jTextNombre_Usuario.requestFocus();
            return;
        }

        if (jTextApellido_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Apellido");
            jTextApellido_Usuario.requestFocus();
            return;
        }

        if (jTextDomicilio_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Domicilio");
            jTextDomicilio_Usuario.requestFocus();
            return;
        }

        if (jTextNomUser_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre de Usuario");
            jTextNomUser_Usuario.requestFocus();
            return;
        }

        if (jTextPass_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una Contraseña");
            jTextPass_Usuario.requestFocus();
            return;
        }

        int cantidad = funcion.ExistenciaUsuarios();

        if (cantidad == 0) {
            JOptionPane.showMessageDialog(null, "Ingreso de datos correctos!, Su Usuario es " + jTextNomUser_Usuario.getText() + " y su contraseña es " + jTextPass_Usuario.getText() + " ");

            vLogin login = new vLogin();
            login.setResizable(false);
            login.toFront();
            login.setLocationRelativeTo(null);
            login.setVisible(true);

            setVisible(false);
        }

        int dato = funcion.VerificarLogin();

        if (dato > 0) {
            JOptionPane.showMessageDialog(this,"Nombre de usuario '" + jTextNomUser_Usuario.getText() + "' ocupado");
            jTextDomicilio_Usuario.setText("");
            jTextCorreo_Usuario.setText("");
            jTextTelefono_Usuario.setText("");
            jTextNomUser_Usuario.setText("");
            jTextPass_Usuario.setText("");
            jTextNombre_Usuario.requestFocus();
            return;
        }

        datos.setNombre_persona(jTextNombre_Usuario.getText());
        datos.setApellido_persona(jTextApellido_Usuario.getText());
        datos.setDomicilio_persona(jTextDomicilio_Usuario.getText());
        datos.setTelefonoContacto_persona(jTextTelefono_Usuario.getText());
        datos.setEmailContacto_persona(jTextCorreo_Usuario.getText());
        datos.setNombre_usuario(jTextNomUser_Usuario.getText());
        datos.setContraseña_usuario(jTextPass_Usuario.getText());

        int acceso = jComboAcceso_Usuario.getSelectedIndex();
        datos.setTipo_usario((String) jComboAcceso_Usuario.getItemAt(acceso));

        int estado = jComboEstado_Usuario.getSelectedIndex();

        if (estado == 0) {
            boolean boolean1 = Boolean.parseBoolean("true");
            datos.setEstado_usuario(boolean1);
        } else {
            boolean boolean2 = Boolean.parseBoolean("false");
            datos.setEstado_usuario(boolean2);
        }

        if (funcion.InsertarUsuarios(datos)) {
            JOptionPane.showMessageDialog(null, "Ingreso de datos Correctos.");
            Mostrar();
            ocultar_columnas();
            Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido ingresar los datos.");
        }
    }//GEN-LAST:event_jBotonAcep_UsuarioActionPerformed

    private void jBotonSalir_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSalir_UsuarioActionPerformed

        vMenu menu = new vMenu();

        menu.setVisible(true);
        menu.setSize(794, 566);
        menu.setResizable(false);
        menu.setLocationRelativeTo(null);

        vMenu.jEtiqUserCndo_Menu.setText(vLogin.jTextNomUser_Login.getText());

        this.setVisible(false);
    }//GEN-LAST:event_jBotonSalir_UsuarioActionPerformed


    private void jBotonModif_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonModif_UsuarioActionPerformed

        mUsuario datos = new mUsuario();
        cUsuario funcion = new cUsuario();

        if (jTextID_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el N° a modificar");
            return;
        }

        if (jTextNombre_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Nombre");
            jTextNombre_Usuario.requestFocus();
            return;
        }

        if (jTextApellido_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Apellido");
            jTextApellido_Usuario.requestFocus();
            return;
        }

        if (jTextDomicilio_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Domicilio");
            jTextDomicilio_Usuario.requestFocus();
            return;
        }

        if (jTextNomUser_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre de Usuario");
            jTextNomUser_Usuario.requestFocus();
            return;
        }

        if (jTextPass_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una contraseña");
            jTextPass_Usuario.requestFocus();
            return;
        }

        /*int dato = funcion.VerificarLogin();

        if (dato >= 1) {
            JOptionPane.showMessageDialog(null, "Nombre de usuario '" + jTextNomUser_Usuario.getText() + "' ocupado");
            jTextNomUser_Usuario.requestFocus();
            return;
        }*/

        datos.setId_persona(Integer.parseInt(jTextID_Usuario.getText()));
        datos.setNombre_persona(jTextNombre_Usuario.getText());
        datos.setApellido_persona(jTextApellido_Usuario.getText());
        datos.setDomicilio_persona(jTextDomicilio_Usuario.getText());
        datos.setTelefonoContacto_persona(jTextTelefono_Usuario.getText());
        datos.setEmailContacto_persona(jTextCorreo_Usuario.getText());
        datos.setNombre_usuario(jTextNomUser_Usuario.getText());
        datos.setContraseña_usuario(jTextPass_Usuario.getText());
        datos.setId_usuario(Integer.parseInt(jTextID_Usuario.getText()));

        int acceso = jComboAcceso_Usuario.getSelectedIndex();
        datos.setTipo_usario((String) jComboAcceso_Usuario.getItemAt(acceso));

        int estado = jComboEstado_Usuario.getSelectedIndex();

        if (estado == 0) {
            boolean boolean1 = Boolean.parseBoolean("true");
            datos.setEstado_usuario(boolean1);
        } else {
            boolean boolean2 = Boolean.parseBoolean("false");
            datos.setEstado_usuario(boolean2);
        }

        if (funcion.EditarUsuarios(datos)) {
            JOptionPane.showMessageDialog(null, "Modificación Exitosa");
            Mostrar();
            ocultar_columnas();
            Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Modificación sin exito, verifique haber ingresado bien los datos u el N° que identifica al usuario");
        }

    }//GEN-LAST:event_jBotonModif_UsuarioActionPerformed

    private void jBotonElim_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonElim_UsuarioActionPerformed
       
        
        int i = JOptionPane.showConfirmDialog(this, "Eliminar Usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (i == 0) {
            jTextID_Usuario.setVisible(true);
            jEtiqID_Usuario.setVisible(true);
            if (!jTextID_Usuario.getText().equals("")) {

                mUsuario datos1 = new mUsuario();
                cUsuario funcion = new cUsuario();

                datos1.setId_persona(Integer.parseInt(jTextID_Usuario.getText()));

                if (funcion.EliminarUsuarios(datos1)) {
                    JOptionPane.showMessageDialog(null, "Se elimino Usuario");
                    Mostrar();
                    ocultar_columnas();
                } else {
                    JOptionPane.showMessageDialog(null, "No se elimino Usuario, ingrese el N° que identifica dicho usuario para realizar la accion necesaria");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el N° a eliminar");
            }
        }
    }//GEN-LAST:event_jBotonElim_UsuarioActionPerformed

    private void jTextNombre_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombre_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jTextApellido_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jTextNombre_UsuarioKeyPressed

    private void jTextApellido_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellido_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jTextDomicilio_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jTextApellido_UsuarioKeyPressed

    private void jTextDomicilio_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDomicilio_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jTextTelefono_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jTextDomicilio_UsuarioKeyPressed

    private void jTextTelefono_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelefono_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jTextCorreo_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jTextTelefono_UsuarioKeyPressed

    private void jTextCorreo_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCorreo_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jTextNomUser_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jTextCorreo_UsuarioKeyPressed

    private void jTextNomUser_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNomUser_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jTextPass_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jTextNomUser_UsuarioKeyPressed

    private void jTextPass_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPass_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jComboAcceso_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jTextPass_UsuarioKeyPressed

    private void jComboAcceso_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboAcceso_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            jComboEstado_Usuario.requestFocus();
        }
    }//GEN-LAST:event_jComboAcceso_UsuarioKeyPressed

    private void jBotonAcep_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBotonAcep_UsuarioKeyPressed
      if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        
        cUsuario funcion = new cUsuario();
        mUsuario datos = new mUsuario();

        if (jTextNombre_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Nombre");
            jTextNombre_Usuario.requestFocus();
            return;
        }

        if (jTextApellido_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Apellido");
            jTextApellido_Usuario.requestFocus();
            return;
        }

        if (jTextDomicilio_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Domicilio");
            jTextDomicilio_Usuario.requestFocus();
            return;
        }

        if (jTextNomUser_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre de Usuario");
            jTextNomUser_Usuario.requestFocus();
            return;
        }

        if (jTextPass_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una Contraseña");
            jTextPass_Usuario.requestFocus();
            return;
        }

        int cantidad = funcion.ExistenciaUsuarios();

        if (cantidad == 0) {
            JOptionPane.showMessageDialog(null, "Ingreso de datos correctos!, Su Usuario es " + jTextNomUser_Usuario.getText() + " y su contraseña es " + jTextPass_Usuario.getText() + " ");

            vLogin login = new vLogin();
            login.setResizable(false);
            login.toFront();
            login.setLocationRelativeTo(null);
            login.setVisible(true);

            setVisible(false);
        }

        int dato = funcion.VerificarLogin();

        if (dato > 0) {
            JOptionPane.showMessageDialog(this, "Nombre de usuario " + jTextNomUser_Usuario.getText() + " ocupado");
            jTextNomUser_Usuario.requestFocus();
            return;
        }

        datos.setNombre_persona(jTextNombre_Usuario.getText());
        datos.setApellido_persona(jTextApellido_Usuario.getText());
        datos.setDomicilio_persona(jTextDomicilio_Usuario.getText());
        datos.setTelefonoContacto_persona(jTextTelefono_Usuario.getText());
        datos.setEmailContacto_persona(jTextCorreo_Usuario.getText());
        datos.setNombre_usuario(jTextNomUser_Usuario.getText());
        datos.setContraseña_usuario(jTextPass_Usuario.getText());

        int acceso = jComboAcceso_Usuario.getSelectedIndex();
        datos.setTipo_usario((String) jComboAcceso_Usuario.getItemAt(acceso));

        int estado = jComboEstado_Usuario.getSelectedIndex();

        if (estado == 0) {
            boolean boolean1 = Boolean.parseBoolean("true");
            datos.setEstado_usuario(boolean1);
        } else {
            boolean boolean2 = Boolean.parseBoolean("false");
            datos.setEstado_usuario(boolean2);
        }

        if (funcion.InsertarUsuarios(datos)) {
            JOptionPane.showMessageDialog(null, "Ingreso de datos Correctos.");
            Mostrar();
            ocultar_columnas();
            Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "No se ha podido ingresar los datos.");
        }
      }
    }//GEN-LAST:event_jBotonAcep_UsuarioKeyPressed

    private void jBotonModif_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBotonModif_UsuarioKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        
        mUsuario datos = new mUsuario();
        cUsuario funcion = new cUsuario();

        if (jTextID_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Ingrese el N° a modificar");
            return;
        }

        if (jTextNombre_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Nombre");
            jTextNombre_Usuario.requestFocus();
            return;
        }

        if (jTextApellido_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar Apellido");
            jTextApellido_Usuario.requestFocus();
            return;
        }

        if (jTextDomicilio_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Domicilio");
            jTextDomicilio_Usuario.requestFocus();
            return;
        }

        if (jTextNomUser_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un nombre de Usuario");
            jTextNomUser_Usuario.requestFocus();
            return;
        }

        if (jTextPass_Usuario.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una contraseña");
            jTextPass_Usuario.requestFocus();
            return;
        }

        int dato = funcion.VerificarLogin();

        if (dato > 1) {
            JOptionPane.showMessageDialog(this, "Nombre de usuario " + jTextNomUser_Usuario.getText() + " ocupado");
            jTextNomUser_Usuario.requestFocus();
            return;
        }

        datos.setId_persona(Integer.parseInt(jTextID_Usuario.getText()));
        datos.setNombre_persona(jTextNombre_Usuario.getText());
        datos.setApellido_persona(jTextApellido_Usuario.getText());
        datos.setDomicilio_persona(jTextDomicilio_Usuario.getText());
        datos.setTelefonoContacto_persona(jTextTelefono_Usuario.getText());
        datos.setEmailContacto_persona(jTextCorreo_Usuario.getText());
        datos.setNombre_usuario(jTextNomUser_Usuario.getText());
        datos.setContraseña_usuario(jTextPass_Usuario.getText());
        datos.setId_usuario(Integer.parseInt(jTextID_Usuario.getText()));

        int acceso = jComboAcceso_Usuario.getSelectedIndex();
        datos.setTipo_usario((String) jComboAcceso_Usuario.getItemAt(acceso));

        int estado = jComboEstado_Usuario.getSelectedIndex();

        if (estado == 0) {
            boolean boolean1 = Boolean.parseBoolean("true");
            datos.setEstado_usuario(boolean1);
        } else {
            boolean boolean2 = Boolean.parseBoolean("false");
            datos.setEstado_usuario(boolean2);
        }

        if (funcion.EditarUsuarios(datos)) {
            JOptionPane.showMessageDialog(null, "Modificación Exitosa");
            Mostrar();
            ocultar_columnas();
            Limpiar();
        } else {
            JOptionPane.showMessageDialog(null, "Modificación sin exito, verifique haber ingresado bien los datos u el N° que identifica al usuario");
        }
       }
    }//GEN-LAST:event_jBotonModif_UsuarioKeyPressed

    private void jBotonElim_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBotonElim_UsuarioKeyPressed
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        int i = JOptionPane.showConfirmDialog(this, "Eliminar Usuario?", "Confirmar", JOptionPane.YES_NO_OPTION);

        if (i == 0) {
            jTextID_Usuario.setVisible(true);
            jEtiqID_Usuario.setVisible(true);
            if (!jTextID_Usuario.getText().equals("")) {

                mUsuario datos1 = new mUsuario();
                cUsuario funcion = new cUsuario();

                datos1.setId_persona(Integer.parseInt(jTextID_Usuario.getText()));

                if (funcion.EliminarUsuarios(datos1)) {
                    JOptionPane.showMessageDialog(null, "Se elimino Usuario");
                    Mostrar();
                    ocultar_columnas();
                } else {
                    JOptionPane.showMessageDialog(null, "No se elimino Usuario, ingrese el N° que identifica dicho usuario para realizar la accion necesaria");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese el N° a eliminar");
            }
        }
        }
    }//GEN-LAST:event_jBotonElim_UsuarioKeyPressed

    private void jBotonSalir_UsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBotonSalir_UsuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            vMenu menu = new vMenu();

            menu.setVisible(true);
            menu.setSize(794, 566);
            menu.setResizable(false);
            menu.setLocationRelativeTo(null);

            vMenu.jEtiqUserCndo_Menu.setText(vLogin.jTextNomUser_Login.getText());

            this.setVisible(false);
        }
        }
    }//GEN-LAST:event_jBotonSalir_UsuarioKeyPressed

    private void jBotonCancel_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonCancel_UsuarioActionPerformed
 
       Limpiar();
       jBotonElim_Usuario.setEnabled(false);
       jBotonModif_Usuario.setEnabled(false);
       jBotonCancel_Usuario.setVisible(false);
       jBotonAcep_Usuario.setEnabled(true);
    }//GEN-LAST:event_jBotonCancel_UsuarioActionPerformed

    private void jBotonSalir2_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSalir2_UsuarioActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jBotonSalir2_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vGestion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vGestion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vGestion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vGestion_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vGestion_Usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JSP1_Usuario;
    private javax.swing.JLabel LTit_Usuario;
    private javax.swing.JButton jBotonAcep_Usuario;
    private javax.swing.JButton jBotonCancel_Usuario;
    private javax.swing.JButton jBotonElim_Usuario;
    private javax.swing.JButton jBotonModif_Usuario;
    public static javax.swing.JButton jBotonSalir2_Usuario;
    public static javax.swing.JButton jBotonSalir_Usuario;
    public static javax.swing.JComboBox<String> jComboAcceso_Usuario;
    public static javax.swing.JComboBox<String> jComboEstado_Usuario;
    private javax.swing.JLabel jEtiqAcceso_Usuario;
    private javax.swing.JLabel jEtiqApellido_Usuario;
    private javax.swing.JLabel jEtiqCorreo_Usuario;
    private javax.swing.JLabel jEtiqDomicilio_Usuario;
    private javax.swing.JLabel jEtiqEstado_Usuario;
    private javax.swing.JLabel jEtiqID_Usuario;
    private javax.swing.JLabel jEtiqNomUser_Usuario;
    private javax.swing.JLabel jEtiqNombre_Usuario;
    private javax.swing.JLabel jEtiqPass_Usuario;
    private javax.swing.JLabel jEtiqTelefono_Usuario;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTabla_Usuario;
    public static javax.swing.JTextField jTextApellido_Usuario;
    public static javax.swing.JTextField jTextCorreo_Usuario;
    public static javax.swing.JTextField jTextDomicilio_Usuario;
    private javax.swing.JTextField jTextID_Usuario;
    public static javax.swing.JTextField jTextNomUser_Usuario;
    public static javax.swing.JTextField jTextNombre_Usuario;
    public static javax.swing.JTextField jTextPass_Usuario;
    public static javax.swing.JTextField jTextTelefono_Usuario;
    // End of variables declaration//GEN-END:variables
}
