/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.cUsuario;
import java.awt.event.KeyEvent;

/**
 *
 * @author Colo-PC
 */
public class vMenu extends javax.swing.JFrame {

    /**
     * Creates new form vMenu
     */
    public vMenu() {
        initComponents();
        jIconUser_Menu.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTitUser_Menu = new javax.swing.JLabel();
        jEtiqUserCndo_Menu = new javax.swing.JLabel();
        jBotonSalir_Menu = new javax.swing.JButton();
        jIconUser_Menu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jFMenu\n"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTitUser_Menu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTitUser_Menu.setText("Usuarios");
        getContentPane().add(jTitUser_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, 20));

        jEtiqUserCndo_Menu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        getContentPane().add(jEtiqUserCndo_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, 70, 30));

        jBotonSalir_Menu.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jBotonSalir_Menu.setText("Salir");
        jBotonSalir_Menu.setFocusable(false);
        jBotonSalir_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSalir_MenuActionPerformed(evt);
            }
        });
        jBotonSalir_Menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jBotonSalir_MenuKeyPressed(evt);
            }
        });
        getContentPane().add(jBotonSalir_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        jIconUser_Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        jIconUser_Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jIconUser_MenuMouseClicked(evt);
            }
        });
        jIconUser_Menu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jIconUser_MenuKeyPressed(evt);
            }
        });
        getContentPane().add(jIconUser_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 10, 200, 180));

        setSize(new java.awt.Dimension(794, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonSalir_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSalir_MenuActionPerformed

        cUsuario funcion = new cUsuario();
        funcion.cerrarEstado();

        vLogin login1 = new vLogin();

        login1.setSize(275, 495);
        login1.setVisible(true);
        login1.setResizable(false);
        login1.setLocationRelativeTo(null);

        this.setVisible(false);
    }//GEN-LAST:event_jBotonSalir_MenuActionPerformed

    private void jBotonSalir_MenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBotonSalir_MenuKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        cUsuario funcion = new cUsuario();
        funcion.cerrarEstado();

        vLogin login1 = new vLogin();

        login1.setSize(275, 495);
        login1.setVisible(true);
        login1.setResizable(false);
        login1.setLocationRelativeTo(null);

        this.setVisible(false);
        }
    }//GEN-LAST:event_jBotonSalir_MenuKeyPressed

    private void jIconUser_MenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jIconUser_MenuKeyPressed
       
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
        vGestion_Usuarios usuarios = new vGestion_Usuarios();

        usuarios.setResizable(false);
        usuarios.setLocationRelativeTo(null);
        usuarios.setVisible(true);
        usuarios.toFront();

        this.setVisible(false);
        }
    }//GEN-LAST:event_jIconUser_MenuKeyPressed

    private void jIconUser_MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jIconUser_MenuMouseClicked
        vGestion_Usuarios usuarios = new vGestion_Usuarios();

        usuarios.setResizable(false);
        usuarios.setLocationRelativeTo(null);
        usuarios.setVisible(true);
        usuarios.toFront();

        this.setVisible(false);
    }//GEN-LAST:event_jIconUser_MenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new vMenu().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonSalir_Menu;
    public static javax.swing.JLabel jEtiqUserCndo_Menu;
    public static javax.swing.JLabel jIconUser_Menu;
    public static javax.swing.JLabel jTitUser_Menu;
    // End of variables declaration//GEN-END:variables
}
