/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.control_PagosEmpleados;
import Controlador.control_TiposEmpleados;
import Modelo.Session;
import Modelo.TiposEmpleados;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JOptionPane;

/**
 *
 * @author CRISTIAN
 */
public class vPagos_Empleados extends javax.swing.JInternalFrame{
    control_TiposEmpleados control_te = new control_TiposEmpleados();
    
    //vCerrar_Caja vcerrar_caja = new vCerrar_Caja();
   
    /**
     * Creates new form vPagos_Empleados
     */
    public vPagos_Empleados() {
        initComponents();     
        //System.out.println(vcerrar_caja.editadoPagoEmpleados);
        if(Session.isEditadoPagoEmpleados()){
            mostrarDatos();
        }else{
            iniciar();
            calcularTotalesIniciales();
        }
        
        /*jTextCajero.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {               
                calcularTotales();
            }
            @Override
            public void focusLost(FocusEvent e) {
                calcularTotales();
            }
        });*/
        
    }
    private void mostrarDatos(){
        jTextCajero.setText(Float.toString(Session.fCajero));
        jTextCocinero.setText(Float.toString(Session.fCocinero));
        jTextPizzero.setText(Float.toString(Session.fPizzero));
        jTextCadete1.setText(Float.toString(Session.fCadete1));
        jTextCadete2.setText(Float.toString(Session.fCadete2));     
        jTextCadete3.setText(Float.toString(Session.fCadete3)); 
        jTextCadete4.setText(Float.toString(Session.fCadete4)); 
    }
    
    private void iniciar(){
        jTextCajero.setText("0");
        jTextCocinero.setText("0");
        jTextPizzero.setText("0");
        jTextCadete1.setText("0");
        jTextCadete2.setText("0");     
        jTextCadete3.setText("0"); 
        jTextCadete4.setText("0"); 
        
    }
    
    private void calcularTotalesIniciales(){
        TiposEmpleados te = new TiposEmpleados();
        float total_cajeros = control_te.getTotalSueldo(2);
        float total_cocineros = control_te.getTotalSueldo(3);
        float total_pizzeros = control_te.getTotalSueldo(4);
        float total_cadete = control_te.getTotalSueldo(5);
        jTextCajero.setText(Float.toString(total_cajeros));
        jTextCocinero.setText(Float.toString(total_cocineros));
        jTextPizzero.setText(Float.toString(total_pizzeros));
        jTextCadete1.setText(Float.toString(total_cadete));
        jTextCadete2.setText(Float.toString(total_cadete));     
        jTextCadete3.setText(Float.toString(total_cadete)); 
        jTextCadete4.setText(Float.toString(total_cadete)); 
        float total = total_cajeros+total_cocineros+total_pizzeros+total_cadete*4;
        jTexTotal.setText(Float.toString(total));
    }
    
     public void calcularTotales(){
        float total_cajeros = Float.valueOf(jTextCajero.getText());
        float total_cocineros = Float.valueOf(jTextCocinero.getText());
        float total_pizzeros = Float.valueOf(jTextPizzero.getText());
        float total_cadete1 = Float.valueOf(jTextCadete1.getText());
        float total_cadete2 = Float.valueOf(jTextCadete2.getText());
        float total_cadete3 = Float.valueOf(jTextCadete3.getText());
        float total_cadete4 = Float.valueOf(jTextCadete4.getText());
        float total = total_cajeros+total_cocineros+total_pizzeros+total_cadete1+total_cadete2+total_cadete3+total_cadete4;
        jTexTotal.setText(Float.toString(total));
     }
     
    public void setControlador(control_PagosEmpleados cpe) {
        jTextCajero.addActionListener(cpe);
        jTextCajero.addFocusListener(cpe);
        jTextCocinero.addActionListener(cpe);
        jTextCocinero.addFocusListener(cpe);
        jTextPizzero.addActionListener(cpe);
        jTextPizzero.addFocusListener(cpe);
        jTextCadete1.addActionListener(cpe);
        jTextCadete1.addFocusListener(cpe);
        jTextCadete2.addActionListener(cpe);
        jTextCadete2.addFocusListener(cpe);
        jTextCadete3.addActionListener(cpe);
        jTextCadete3.addFocusListener(cpe);
        jTextCadete4.addActionListener(cpe);
        jTextCadete4.addFocusListener(cpe);
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextCajero = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextCocinero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextPizzero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextCadete1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextCadete2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextCadete3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextCadete4 = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTexTotal = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 248, 177));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pagos a Empleados");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoDelivery.png"))); // NOI18N
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel1.setText("Cajero:");

        jTextCajero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel2.setText("Cocinero:");

        jTextCocinero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel3.setText("Pizzero:");

        jTextPizzero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel4.setText("Cadete 1:");

        jTextCadete1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel5.setText("Cadete 2:");

        jTextCadete2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel6.setText("Cadete 3:");

        jTextCadete3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel7.setText("Cadete 4:");

        jTextCadete4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        btnAceptar.setBackground(new java.awt.Color(252, 249, 57));
        btnAceptar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(237, 124, 61));
        btnCancelar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        jLabel8.setText("TOTAL:");

        jTexTotal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextCajero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCocinero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextPizzero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCadete1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCadete2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCadete3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCadete4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jTexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCajero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCocinero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPizzero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCadete1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCadete2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCadete3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCadete4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTexTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setearDatosVentana(){
        Session.fCajero = Float.valueOf(jTextCajero.getText());
        Session.fCocinero = Float.valueOf(jTextCocinero.getText());
        Session.fPizzero = Float.valueOf(jTextPizzero.getText());
        Session.fCadete1 = Float.valueOf(jTextCadete1.getText());
        Session.fCadete2 = Float.valueOf(jTextCadete2.getText());
        Session.fCadete3 = Float.valueOf(jTextCadete3.getText());
        Session.fCadete4 = Float.valueOf(jTextCadete4.getText());
    }
    
    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //guardamos los datos de la ventana en atributos
        setearDatosVentana();
        Session.setEditadoPagoEmpleados(true);
        //actualizamos la ventana de Cierre de Caja
        //vCerrar_Caja vcerrar_caja = new vCerrar_Caja();
        float total_pagos = Float.valueOf(jTexTotal.getText());
        vCerrar_Caja.jTextEmpleados.setText(Float.toString(total_pagos));
                
        //vMenuPrincipal.jDesktopPane1.add(vcerrar_caja);
        //vcerrar_caja.show();
        this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        iniciar();
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        if(!jTextCajero.getText().equals("0.0") || !jTextPizzero.getText().equals("0.0") || !jTextCocinero.getText().equals("0.0") || !jTextCadete1.getText().equals("0.0") || !jTextCadete2.getText().equals("0.0") || !jTextCadete3.getText().equals("0.0") || !jTextCadete4.getText().equals("0.0")){
            int i=JOptionPane.showConfirmDialog(null, "Esta seguro de salir?","Confirmar",JOptionPane.YES_OPTION);
            if(i==0){
                dispose();
            } else {
                setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField jTexTotal;
    public javax.swing.JTextField jTextCadete1;
    public javax.swing.JTextField jTextCadete2;
    public javax.swing.JTextField jTextCadete3;
    public javax.swing.JTextField jTextCadete4;
    public javax.swing.JTextField jTextCajero;
    public javax.swing.JTextField jTextCocinero;
    public javax.swing.JTextField jTextPizzero;
    // End of variables declaration//GEN-END:variables
}
